version: '3.8'

volumes:
  modules:
  databaseData:

networks:
  internalRedis:
  internalPrometheus:

services:
  TSSmartHomeDev:
    image: ts-smarthome:dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      # API Folders
      - ./:/workspace:cached
      - modules:/workspace/node_modules
    networks:
      - internalRedis
      - internalPrometheus

  Redis:
    image: redis:alpine3.12
    networks:
      - internalRedis
