version: '3.8'

volumes:
  modules:
  databaseData:

networks:
  internalDB:
  internalRedis:
  internalPrometheus:

services:
  TSSmartHomeDev:
    image: ts-smarthome:dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      # API Folders
      - ./:/workspace:cached
      - modules:/workspace/node_modules
    networks:
      - internalDB
      - internalRedis
      - internalPrometheus

  Database:
    image: postgres:alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    networks:
      - internalDB
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ts-smarthome

  Redis:
    image: redis:alpine3.12
    networks:
      - internalRedis
